# Control Points
# We create control points following this convention:
#
#  fl --- fc --- fr
#  |              |
# mfl      x     mfr
#  |       |      |
#  ml  y- mc     mr
#  |              |
# mbl            mbr
#  |              |
#  bl --- bc --- br
#
# where the indices are given counterclockwise from the x-axis
#  
#  0: fc:  front-center
#  1: fl:  front-left
#  2: mfl: mid front-left
#  3: ml:  mid-left
#  4: mbl: mid back-left
#  5: bl:  back-left
#  6: bc:  back-center
#  7: br:  back-right
#  8: mbr: mid back-right
#  9: mr:  mid-right
# 10: mfl: mid front-right
# 11: fr:  front-right
# 12: mc:  mid-center
#

control_points:
  mc :
    point_factor: [0.0, 0.0]
    affected_by_goal: false
    affected_by_obstacle: true
    color: [0.00, 0.00, 0.00]
    radius: 0.35
  flc :
    point_factor: [0.6, 0.3]
    affected_by_goal: false
    affected_by_obstacle: true
    color: [0.00, 0.00, 0.00]
    radius: 0.3
  frc :
    point_factor: [0.6, -0.3]
    affected_by_goal: false
    affected_by_obstacle: true
    color: [0.00, 0.00, 0.00]
    radius: 0.3
  blc :
    point_factor: [-0.6, 0.3]
    affected_by_goal: false
    affected_by_obstacle: true
    color: [0.00, 0.00, 0.00]
    radius: 0.3
  brc :
    point_factor: [-0.6, -0.3]
    affected_by_goal: false
    affected_by_obstacle: true
    color: [0.00, 0.00, 0.00]
    radius: 0.3

# control_points:
#   mc :
#     point_factor: [0.0, 0.0]
#     affected_by_goal: false
#     affected_by_obstacle: true
#     color: [0.00, 0.00, 0.00]
#     radius: 0.35
#   fc :
#     point_factor: [0.6, 0.0]
#     affected_by_goal: false
#     affected_by_obstacle: true
#     color: [0.00, 0.00, 0.00]
#     radius: 0.35
#   bc :
#     point_factor: [-0.6, 0.0]
#     affected_by_goal: false
#     affected_by_obstacle: true
#     color: [0.00, 0.00, 0.00]
#     radius: 0.35
#   fc :
#     point_factor: [1.0, 0.0]
#     affected_by_goal: true
#     affected_by_obstacle: true
#     color: [1.00, 0.00, 0.00]
#     radius: 0.1
#   fl :
#     point_factor: [1.0, 1.0]
#     affected_by_goal: false
#     affected_by_obstacle: true
#     color: [1.00, 0.46, 0.00]
#     radius: 0.1
#   mfl:
#     point_factor: [0.5, 1.0]
#     affected_by_goal: false
#     affected_by_obstacle: true
#     color: [1.00, 0.92, 0.00]
#     radius: 0.1
#   ml :
#     point_factor: [0.0, 1.0]
#     affected_by_goal: false
#     affected_by_obstacle: true
#     color: [0.62, 1.00, 0.00]
#     radius: 0.1
#   mbl:
#     point_factor: [-0.5, 1.0]
#     affected_by_goal: false
#     affected_by_obstacle: true
#     color: [0.15, 1.00, 0.00]
#     radius: 0.1
#   bl :
#     point_factor: [-1.0, 1.0]
#     affected_by_goal: false
#     affected_by_obstacle: true
#     color: [0.00, 1.00, 0.31]
#     radius: 0.1
#   bc :
#     point_factor: [-1.0, 0.0]
#     affected_by_goal: false
#     affected_by_obstacle: true
#     color: [0.00, 1.00, 0.77]
#     radius: 0.1
#   br :
#     point_factor: [-1.0, -1.0]
#     affected_by_goal: false
#     affected_by_obstacle: true
#     color: [0.00, 0.77, 1.00]
#     radius: 0.1
#   mbr:
#     point_factor: [-0.5, -1.0]
#     affected_by_goal: false
#     affected_by_obstacle: true
#     color: [0.00, 0.31, 1.00]
#     radius: 0.1
#   mr :
#     point_factor: [0.0, -1.0]
#     affected_by_goal: false
#     affected_by_obstacle: true
#     color: [0.15, 0.00, 1.00]
#     radius: 0.1
#   mfr:
#     point_factor: [0.5, -1.0]
#     affected_by_goal: false
#     affected_by_obstacle: true
#     color: [0.62, 0.00, 1.00]
#     radius: 0.1
#   fr :
#     point_factor: [1.0, -1.0]
#     affected_by_goal: false
#     affected_by_obstacle: true
#     color: [1.00, 0.00, 0.92]
#     radius: 0.1
#   mc :
#     point_factor: [0.0, 0.0]
#     affected_by_goal: false
#     affected_by_obstacle: false
#     color: [1.00, 0.00, 0.46]
#     radius: 0.1